INDUSTRIES = ['Advertising, Branding & Marketing',
              'Alternative & Renewable Energy',
              'Apparel, Textiles & Fashions',
              'Automobiles & Trucks',
              'Banking, Mortgages, Credit, Investment & Securities',
              'Biotechnology, Drugs & Genetics',
              'Chemicals, Coatings & Plastics',
              'Computers, Software, & InfoTech', 
              'Communications & Social Media',
              'Consulting, Outsourcing, Offshoring',
              'E-Commerce & Internet Based Services',
              'Education',
              'Entertainment & Media',
              'Food, Beverages & Tobacco', 
              'Games, Apps & Social',
              'Health Care',
              'Insurance & Risk Management',
              'Nanotechnology',
              'Real Estate & Construction',
              'Retail',
              'Sports and Recreation',
              'Transportation, Supply Chain & Logistics',
              'Travel, Airlines, Hotels & Tourism',
              'Utilities',
              'Wireless',
              'Other']

STATES = ['Alabama',
          'Alaska',
          'Arizona',
          'Arkansas',
          'California',
          'Colorado',
          'Connecticut',
          'Delaware',
          'District of Columbia',
          'Florida',
          'Georgia',
          'Hawaii',
          'Idaho',
          'Illinois',
          'Indiana',
          'Iowa',
          'Kansas',
          'Kentucky',
          'Louisiana',
          'Maine',
          'Maryland',
          'Massachusetts',
          'Michigan',
          'Minnesota',
          'Mississippi',
          'Missouri',
          'Montana',
          'Nebraska',
          'Nevada',
          'New Hampshire',
          'New Jersey',
          'New Mexico',
          'New York',
          'North Carolina',
          'North Dakota',
          'Ohio',
          'Oklahoma',
          'Oregon',
          'Pennsylvania',
          'Rhode Island',
          'South Carolina',
          'South Dakota',
          'Tennessee',
          'Texas',
          'Utah',
          'Vermont',
          'Virginia',
          'Washington',
          'West Virginia',
          'Wisconsin',
          'Wyoming']

GREETINGS = [{:greeting => "Hello", :language => "English"},
             {:greeting => "Howdy", :language => "Texan"},
             {:greeting => "Konichi Wa", :language => "Japanese"},
             {:greeting => "Ahoj", :language => "Slovak"},
             {:greeting => "Hello", :language => "English"},
             {:greeting => "Hola", :language => "Spanish"},
             {:greeting => "Hallo", :language => "Afrikaans"},
             {:greeting => "Salam", :language => "Azerbaijani"},
             {:greeting => "Kaixo", :language => "Basque"},
             {:greeting => "Namaste", :language => "Hindi"},
             {:greeting => "Sua s'dei", :language => "Cambodian"},
             {:greeting => "Rrrrrrrr", :language => "Shyriiwook (Wookie)"},
             {:greeting => "Nei ho", :language => "Cantonese (Chinese)"},
             {:greeting => "Salaam Alekum", :language => "Arabic"},
             {:greeting => "Bonjour", :language => "French"},
             {:greeting => "Guten Tag", :language => "German"},
             {:greeting => "Godan Dag ", :language => "Icelandic"},
             {:greeting => "Ahn Nyeong Ha Se Yo", :language => "Korean"},
             {:greeting => "Ahoy Matey", :language => "Pirate"},
             {:greeting => "Ola", :language => "Portuguese"},
             {:greeting => "Ciao", :language => "Italian"},
             {:greeting => "Zdravstvuy", :language => "Russian"},
             {:greeting => "Jambo", :language => "Swahili"},
             {:greeting => "Tjenare", :language => "Swedish"},
             {:greeting => "Hoy", :language => "Tagalog (Philippines)"},
             {:greeting => "Aloha", :language => "Hawaiian"}]
